/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 scene.gltf --transform 
Files: scene.gltf [36.94KB] > C:\Users\user\r3fl\assets\scene-transformed.glb [2.67MB] (-7117%)
Author: david.campuzano (https://sketchfab.com/david.campuzano)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hacker-room-stylized-a0cfe6edf2dd494c8a95addf6bb13a10
Title: Hacker Room - Stylized
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.computer_computer_mat_0.geometry} material={materials.computer_mat} />
      <mesh geometry={nodes.server_server_mat_0.geometry} material={materials.server_mat} />
      <mesh geometry={nodes.vhs_vhsPlayer_mat_0.geometry} material={materials.vhsPlayer_mat} />
      <mesh geometry={nodes.shelf_stand_mat_0.geometry} material={materials.stand_mat} />
      <mesh geometry={nodes.keyboard_mat_mat_mat_0.geometry} material={materials.mat_mat} />
      <mesh geometry={nodes.arm_arm_mat_0.geometry} material={materials.arm_mat} />
      <mesh geometry={nodes.Tv_tv_mat_0.geometry} material={materials.tv_mat} />
      <mesh geometry={nodes.table_table_mat_0.geometry} material={materials.table_mat} />
      <mesh geometry={nodes.Cables_cables_mat_0.geometry} material={materials.cables_mat} />
      <mesh geometry={nodes.props_props_mat_0.geometry} material={materials.props_mat} />
      <mesh geometry={nodes.screen_screens_0.geometry} material={materials.screens} />
      <mesh geometry={nodes.screen_glass_glass_0.geometry} material={materials.glass} />
      <mesh geometry={nodes.Ground_ground_mat_0.geometry} material={materials.ground_mat} />
      <mesh geometry={nodes.peripherals_key_mat_0.geometry} material={materials.key_mat} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
